# Server Configuration
server.port=8083

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/db_pedidos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# Application Configuration
spring.application.name=aroma-store-order-service

# User Service Configuration
user.service.url=${USER_SERVICE_URL:http://localhost:8082}
